#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

counter=1

while [ $counter -le 10]
do
	if [ $counter -eq 4 ]; then
		echo "Bad luck"
	elif [ $counter -eq 8 ]; then
		echo "Good Luck"
	else
		echo "Best School"
	fi
done
