#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12]
do
	printf "%02d:%02d\n" "$hour" "$minute"

	(( minute++ ))

	if [$minute -eq 60]; then
		(( minute = 0 ))
		(( hour ++ ))
	fi
done | head -n 70
